name: CI Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ui-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm ci

      - name: Run UI tests with Cucumber
        continue-on-error: true
        run: |
          npm run test:cucumber
      - name: Add artifact with report
        uses: actions/upload-artifact@v4
        with:
          path: ./reports/html-reports/

  api-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm ci

      - name: Run API tests
        run: |
          npm run test:axios
